export enum COURSE_CATEGORIES {
  BASIC = "Basic",
  FRONTEND = "Front-end",
  BACKEND = "Back-end",
  FULLSTACK = "Fullstack",
  AI = "AI",
}

export const COURSE_CATEGORIES_OPTIONS = [
  { value: COURSE_CATEGORIES.BASIC, label: COURSE_CATEGORIES.BASIC },
  { value: COURSE_CATEGORIES.FRONTEND, label: COURSE_CATEGORIES.FRONTEND },
  { value: COURSE_CATEGORIES.BACKEND, label: COURSE_CATEGORIES.BACKEND },
  { value: COURSE_CATEGORIES.FULLSTACK, label: COURSE_CATEGORIES.FULLSTACK },
  { value: COURSE_CATEGORIES.AI, label: COURSE_CATEGORIES.AI },
];
